<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NebuLog.Contracts\NebuLog.Contracts.csproj" />
    <ProjectReference Include="..\..\src\NebuLog.OpenTelemetry\NebuLog.OpenTelemetry.csproj" />
  </ItemGroup>
</Project>
